// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxTTfDZ55yjgHGMvggBRJ5J1Z4JBqal-k',
    appId: '1:954554939276:web:c1c853d29180c3a4f448a9',
    messagingSenderId: '954554939276',
    projectId: 'futibas-c0723',
    authDomain: 'futibas-c0723.firebaseapp.com',
    storageBucket: 'futibas-c0723.appspot.com',
    measurementId: 'G-12P6VT16BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT9nDb2B-zzWzwWhu7UdDevWX2C82ZfVg',
    appId: '1:954554939276:android:50d49e2c7e203006f448a9',
    messagingSenderId: '954554939276',
    projectId: 'futibas-c0723',
    storageBucket: 'futibas-c0723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGLRohWdKAkGkRT2CrG5c14fMiOhRNyI',
    appId: '1:954554939276:ios:1cb6e6d23b385ab8f448a9',
    messagingSenderId: '954554939276',
    projectId: 'futibas-c0723',
    storageBucket: 'futibas-c0723.appspot.com',
    iosClientId: '954554939276-n5br1f7dr927kmrop358b5r8u9utm4gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.futibas',
  );
}
